### PR TITLE
Add exp flow type and some asserts

### PR DESCRIPTION
**Pull request by ohad123**

### CODE REVIEW

**Comment by ohad123** [comment]
Done

**Comment by leondavi** [comment]
@ohad123 @NoaShapira8 
Please take a look at the CI. There is an issue on your side - it fails on some variable definition on APIServer. 
@GuyPerets106 should take it after you solve this bug...

**Review by leondavi — CHANGES_REQUESTED** [review]
Issue in APIServer that doesn't pass CI

**Comment by leondavi** [comment]
I can't approve this PR because there are conflicts with the other PR https://github.com/leondavi/NErlNet/pull/331

**Pull request closed without merging**
