### PR TITLE
Full flow ci

### PR DESCRIPTION
**Pull request by leondavi**

### CODE REVIEW

**Comment by dolby360** [comment]
The build is failing because the old container is being utilized, and the old container does not have pip installed. To address this issue, I recommend two possible solutions:

Create a New Pull Request to Update leondavi/nerlnet:latest (happen only after the merge):
Initiate another pull request (PR) specifically for updating the leondavi/nerlnet:latest container on DockerHub with pip3. This update should only take place after the current PR has been merged.

Create a New TAG and Use It:
Alternatively, you can create a new TAG for the container and then use this updated TAG in your build process. This method provides version control for your containers and allows you to specify which version of the container to use in your builds.

I recommend considering the first option as it is more straightforward and the change is very small.

**Comment by leondavi** [comment]
> The build is failing because the old container is being utilized, and the old container does not have pip installed. To address this issue, I recommend two possible solutions:
> 
> Create a New Pull Request to Update leondavi/nerlnet:latest (happen only after the merge): Initiate another pull request (PR) specifically for updating the leondavi/nerlnet:latest container on DockerHub with pip3. This update should only take place after the current PR has been merged.
> 
> Create a New TAG and Use It: Alternatively, you can create a new TAG for the container and then use this updated TAG in your build process. This method provides version control for your containers and allows you to specify which version of the container to use in your builds.
> 
> I recommend considering the first option as it is more straightforward and the change is very small.

I took the first approach.
It seems to work.
Thanks!!

**Comment by leondavi** [comment]
@GuyPerets106 
NerlnetRun script will be executed from Python using subprocess. 
We need to implement keep alive mechanism where API-Server has a thread that sends repeatedly KPA requests every T ms and main-server responds.
If main server doesn't respond for N KPA then python raises an exception and prints NerlnetRun stderr and stdout. 
Moreover, we need a terminate function that closes Nerlnet appropriately.

**Comment by leondavi** [comment]
@GuyPerets106 
Please upload your latest changes

**Pull request merged**
