### PR TITLE
[SOURCE] Epochs are supported by source

### PR DESCRIPTION
**Pull request by leondavi**
- BatchId can be greater than source piece csv!!!

### CODE REVIEW

**Comment by leondavi** [comment]
@NoaShapira8 @ohad123  
Please add your changes to support batchIdx > Source piece CSV size to this branch/PR

**Comment by leondavi** [comment]
DC file controls epochs but it relevant only to training phase.
This change adds info from ApiServer about source piece phase. Source uses phase to set Epochs to 1 when phase is prediction.

**Review by ohad123 — APPROVED** [review]

**Comment by leondavi** [comment]
@NoaShapira8  @ohad123 
Can You please download this PR and check with debugger or Jupyter notebook that BatchIds arrived as expected with 3-5 epochs?

**Comment by ohad123** [comment]
BatchIds arrive as expected

**Pull request merged**
